### ISSUE TITLE
Error when first interval is up

### ISSUE THREAD

**Issue by hsribei** [rdepena/interval-timer-cli#1]
Hi! Thanks for making this. I'm getting this error while trying to use it:

```
$ interval-timer --intervals 0.1,0.1
Will time [ 0.1, 0.1 ] for  1  sets
Interval:  0 : 6 Current timer:  0 : 0 
time is up 
Interval:  0 : 6 Current timer:  0 : 6 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn festival ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)

```

Any idea how I could fix it? Thanks!

**Comment by rdepena** [comment]
hmm, not sure. Will take a look tonight, thanks for reporting.

**Comment by rdepena** [comment]
Hey @obvio171 looks like this might be an issue with festival, so a few questions: 
- Did you see any failures or warnings during the install ?
- I assume you are running Linux, what distro are you using and what kernel version? 
- What version of node are you targeting?

I will set up a linux VM and give it another go.

**Comment by rdepena** [comment]
Hey @obvio171 I was able to recreate it on Debian wheezy, seems like on Linux Festival needs to be installed manually (or at least with a package manager). 

so in debian/ubuntu you can install it using apt-get:

``` bash
sudo apt-get install festival festvox-kallpc16k
```

Let me know if that fixes it.

**Comment by hsribei** [comment]
Hi! Thanks for looking into it. Doing that fixed the crash, but I still
hear no sound.

On Thu, Feb 18, 2016 at 12:38 AM, Ricardo De Peña notifications@github.com
wrote:

> Hey @obvio171 https://github.com/obvio171 I was able to recreate it on
> Debian wheezy, seems like on Linux Festival needs to be installed manually
> (or at least with a package manager).
> 
> so in debian/ubuntu you can install it using apt-get:
> 
> sudo apt-get install festival festvox-kallpc16k
> 
> Let me know if that fixes it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rdepena/interval-timer-cli/issues/1#issuecomment-185515697
> .

## 

Code is politics.

**Comment by rdepena** [comment]
hmm, ok. Stepping up my virtual machine game; I will install debian desktop and all that, up to now I was using headless debian.

**Comment by rdepena** [comment]
Ok, with the following I got it working in Debian 8:

```
$ sudo apt-get install festival festvox-kallpc16k libnotify-bin
```

re-Install the cli tool (new version):

```
$ npm install --global interval-timer-cli
```

Now you can pass the speak flag

```
$ interval-timer --speak --intervals 0.1,0.1 
```

**Comment by rdepena** [comment]
@obvio171 ping.
